apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mini-newscollector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/dtarim/mini-newscollector.git"   # <<< replace
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
